### ISSUE TITLE
Words position problem

### ISSUE THREAD

**Issue by HuangAdam** [dorisxx/Obsidian-simple-note-quiz#7]
Theme: [California Coast](https://github.com/mgmeyers/obsidian-california-coast-theme)
The position of words is too left.
![Quicker_20220219_133804](https://user-images.githubusercontent.com/46439030/154788073-717433ea-5c90-432e-acc5-164e4034aacc.png)

**Comment by dorisxx** [comment]
Thank you! Will fix.
