### ISSUE TITLE
Suggestion: Add in an option to separate questions by new bullet points

### ISSUE THREAD

**Issue by Kenljs** [dorisxx/Obsidian-simple-note-quiz#8]
I'm sorry if this is not the place for a suggestion. I wasn't sure where to put it. I really appreciate this plug-in! Research shows that esting is the most effective way to study.  
My suggestion is to give more options for how to distinguish between questions. My review notes are not normally separated by a "space" since I just use a bullet list of questions. It would be beneficial if questions could be separated by new " head bullet points"
ie.

 - Question one
      -  answer 
      - answer
- Question two
      - answer 
      - answer 

Thank you for your work on this! I wouldn't know where to begin to create a plug in and this is a tremendous one!

**Comment by dorisxx** [comment]
Yeah, I'll add the option for users to choose what they like to use for separating questions in the next release. Thanks for raising the suggestion!
